kind: pipeline
type: kubernetes
name: Muminst Server Pipeline

steps:
  - name: build-and-push-pr 
    image: plugins/docker
    settings:
      repo: armand1m/muminst-server
      tags:
        - pr-${DRONE_PULL_REQUEST}
        - ${DRONE_COMMIT_SHA}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
      - pull_request

  - name: build-and-push-master
    image: plugins/docker
    settings:
      repo: armand1m/muminst-server
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
      - master
      event:
      - push

  # drone-gke docs:
  # https://github.com/nytimes/drone-gke/blob/master/DOCS.md
  - name: promote-to-production 
    image: nytimes/drone-gke
    environment:
      TOKEN:
        from_secret: gke_service_account
    settings:
      verbose: true
      skip_template: false
      skip_secret_template: true
      cluster: main-cluster
      zone: us-central1-c
      project: prismatic-petal-263719
      namespace: default
      wait_deployments:
        - deployment/muminst-server
      vars:
        image: armand1m/muminst-server:${DRONE_COMMIT_SHA}
    when:
      event:
      - promote
      target:
      - production

  - name: rollback-production
    image: google/cloud-sdk:alpine
    environment:
      SERVICE_ACCOUNT:
        from_secret: gke_service_account
      GOOGLE_APPLICATION_CREDENTIALS: /drone/src/gke-service-account.json
      CLOUDSDK_CORE_DISABLE_PROMPTS: "1"
    commands:
      - echo $SERVICE_ACCOUNT > $GOOGLE_APPLICATION_CREDENTIALS
      - gcloud components install kubectl
      - gcloud config set project prismatic-petal-263719
      - gcloud config set compute/zone us-central1-c
      - gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
      - gcloud container clusters get-credentials main-cluster
      - kubectl rollout undo deployment.v1.apps/muminst-server --namespace=default
    when:
      event:
      - rollback
      target:
      - production

trigger:
  ref:
  - refs/heads/master
  - refs/pull/**
  event:
  - push
  - pull_request
  - promote
  - rollback