kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: muminst-server-pv-claim-csi
  labels:
    app: muminst-server
spec:
  storageClassName: standard-rwo 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: muminst-server
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: muminst-server
      version: v1
  template:
    metadata:
      labels:
        app: muminst-server 
        version: v1
    spec:
      volumes:
      - name: muminst-server-volume
        persistentVolumeClaim:
          claimName: muminst-server-pv-claim-csi
      containers:
      - image: {{.image}}
        imagePullPolicy: IfNotPresent
        name: muminst-server 
        ports:
        - containerPort: 4000
        env:
        - name: PROTO
          value: https
        - name: HOSTNAME
          value: muminst-server.d1m.dev
        - name: PORT
          value: "4000"
        - name: FEATURE_TEXT_MESSAGE_ON_PLAY_ENABLED
          value: "false"
        - name: TELEGRAM_ENABLED
          value: "true"
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-secrets
              key: bot_token
        - name: TELEGRAM_CHAT_ID
          value: "-389514977"
        - name: MUMBLE_ENABLED
          value: "true"
        - name: MUMBLE_URL
          value: intruder.network
        - name: MUMBLE_USERNAME
          value: IdiotaHipocrita
        - name: DISCORD_ENABLED
          value: "true"
        - name: DISCORD_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-secrets
              key: bot_token
        - name: DB_PATH
          value: /app/data/db
        - name: AUDIO_PATH
          value: /app/data/audio
        - name: NODE_ENV
          value: production
        resources:
          requests:
            cpu: 15m
            memory: 100Mi
        volumeMounts:
        - mountPath: /app/data
          name: muminst-server-volume

---
apiVersion: v1
kind: Service
metadata:
  name: muminst-server
  namespace: default
  labels:
    app: muminst-server
spec:
  ports:
  - name: http
    port: 4000
    targetPort: 4000
  selector:
    app: muminst-server

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: muminst-server 
  namespace: default
spec:
  host: muminst-server
  trafficPolicy:
    tls:
      mode: DISABLE

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: muminst-server
  namespace: default
spec:
  hosts:
  - muminst-server.d1m.dev
  - muminst-server.armand1m.dev
  gateways:
  - ingressgateway-workload
  http:
  - match:
    - port: 443
    route:
    - destination:
        host: muminst-server
        port:
          number: 4000
