apiVersion: apps/v1
kind: Deployment
metadata:
  name: muminst-server
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: muminst-server
      version: v1
  template:
    metadata:
      labels:
        app: muminst-server 
        version: v1
    spec:
      volumes:
      - name: muminst-server-volume
        persistentVolumeClaim:
          claimName: muminst-server-pv-claim-csi
      containers:
      - image: IMAGE:TAG 
        imagePullPolicy: IfNotPresent
        name: muminst-server 
        ports:
        - containerPort: 4000
        env:
        - name: PROTO
          value: https
        - name: HOSTNAME
          value: muminst-server.d1m.dev
        - name: PORT
          value: "4000"
        - name: FEATURE_TEXT_MESSAGE_ON_PLAY_ENABLED
          value: "false"
        - name: TELEGRAM_ENABLED
          value: "true"
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-secrets
              key: bot_token
        - name: TELEGRAM_CHAT_ID
          value: "-389514977"
        - name: MUMBLE_ENABLED
          value: "false"
        - name: DISCORD_ENABLED
          value: "true"
        - name: DISCORD_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-secrets
              key: bot_token
        - name: DB_PATH
          value: /app/data/db
        - name: AUDIO_PATH
          value: /app/data/audio
        - name: NODE_ENV
          value: production
        resources:
          limits:
            cpu: 250m 
            memory: 256Mi
          requests:
            cpu: 100m 
            memory: 100Mi
        volumeMounts:
        - mountPath: /app/data
          name: muminst-server-volume
