PROJECT_NAME=$(gcloud config get-value project)
SERVICE_ACCOUNT_NAME="gke-service-account"
SERVICE_ACCOUNT_DISPLAY_NAME="GKE Service Account"
GCLOUD_CREDENTIALS_FOLDER_PATH="$(pwd)/.gcloud-credentials"
GOOGLE_APPLICATION_CREDENTIALS="$GCLOUD_CREDENTIALS_FOLDER_PATH/gke-service-account.json"

export GOOGLE_CLOUD_PROJECT=$PROJECT_NAME
export GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS